#!/bin/bash
if [ "$2" = "A" ]
then
  g++ \
    x/$1.cpp \
    -o ../brutus/A \
    -std=c++17 \
    -g \
    -Wall -Wpedantic -Wextra -Wshadow -Wno-parentheses \
    -Ibits -Itestlib -Iatcoder
fi
if [ "$2" = "B" ]
then
  g++ \
    x/$1.cpp \
    -o ../brutus/B \
    -std=c++17 \
    -g \
    -Wall -Wpedantic -Wextra -Wshadow -Wno-parentheses \
    -Ibits -Itestlib -Iatcoder
fi

if [ "$2" = ""  ]
then
  g++ \
    x/$1.cpp \
    -o out \
    -std=c++17 \
    -g \
    -Wall -Wpedantic -Wextra -Wshadow -Wno-parentheses -Wno-unused-const-variable \
	-Wno-unused-variable \
    -fsanitize=address,undefined \
    -Ibits -Itestlib -Iatcoder \
    -DDEBUG

    # -Wl,--stack -Wl,52000000 \
fi

./out < inp

